language: python
branches:
  only:
    - master
    - develop
    - pingudev
python:
  - "2.7"
matrix:
  - allow_failures:
    - python: 3.5
sudo: false
install:
  - make install
  - make start
before_script:
  - sleep 10
script:
  - make testall
  - make pep8
#after_success:
# - coveralls
