language: python
branches:
  only:
    - master
    - develop
python:
  - "2.7"
  - "3.5"
matrix:
  - allow_failures:
    - python: 3.5
sudo: false
install:
  - make install
  - make start
before_script:
  - sleep 15
script:
  - make testall
#after_success:
# - coveralls
