language: python
branches:
  only:
    - master
    - develop
python:
  - "2.7"
sudo: false
install:
  - make install
  - make start
before_script:
  - sleep 15
script:
  - make docs
  - make testall
#after_success:
# - coveralls
