malleefowl:
  image: birdhouse/malleefowl
  command: make update-config update-user start
  ports:
    - "48091:9001"
    - "38091:38091"
    - "8091:8091"
  volumes:
    - data:/data
  volume_driver: local

