name: malleefowl
channels:
- defaults
- birdhouse
- conda-forge
dependencies:
- python=2.7
- pyopenssl
- cryptography
- libffi
- pyyaml
- curl
# buildout
- mako
# tests
- pytest
- flake8
# ipython
- ipython
# docs
- sphinx
- sphinx_rtd_theme
# wps
- pywps=3.2.6
- lxml=3.6.0
- owslib=0.13.0
- nginx=1.10.1
- supervisor
- gunicorn=19.1.0
- gevent=1.1.1
- eventlet=0.16.1
# malleefowl
- python-dateutil=2.5.3
- netcdf4=1.2.4
- esgf-pyclient=0.1.6
- myproxyclient=1.4.4
- dispel4py=1.0.1
- python-swiftclient=2.4.0
- threddsclient=0.3.4
- pysolr=3.3.2
- wget=1.18
- pip:
  - genshi==0.7
  - sphinx-autoapi==0.4.0
#  - eventlet==0.19.0
